import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useMemo, useState } from 'react'
import styles from '../styles/Home.module.css'
import Cookies from '../utils/Cookies'
import Library from '../utils/Library'
import Urls from '../utils/Urls'
import MainContainer from '../src/components/mains/MainContainer'
import Footer from '../src/components/mains/FooterComponent'
import Constants from '../utils/Constants'
import useWindowDimensions from '../src/components/uses/WindowDimensions'
export default function Home() {
  const library = Library()
  const cookie = Cookies()
  const constants = Constants()
  const urls = Urls()
  const router = useRouter()
  let {height_,width_} = useWindowDimensions()

  useEffect(()=>{
    if(!library.checkLogin()){
      if(library.isMobile()){
        router.push('login','login')
      }
      router.push('login')
    }
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>My Account - AiGooX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer width_={width_} height_={height_}/>
      <Footer />
    </div>
  )
}
